# Generated by Django 5.1.3 on 2024-12-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='food',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='presence',
            field=models.CharField(max_length=1000),
        ),
    ]
