# Generated by Django 5.1.3 on 2024-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='string_ids',
        ),
        migrations.AlterField(
            model_name='friend',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='friend',
            name='item_titles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
