# Generated by Django 5.1.3 on 2025-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_remove_friend_string_ids_alter_friend_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='food',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='allergy',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='camping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='intollerance',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
