# Generated by Django 5.1.3 on 2025-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_remove_rsvp_food_rsvp_allergy_rsvp_camping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='allergy',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='intollerance',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
